python_executable: auto
motion:
  enabled: true
  execute: true
  source_pkl: engines/skill_tracking/example/motion_data/Horse-stance_pose.pkl
  output_dir: runtime/example_motion
  output_file: runtime/example_motion/example_motion.pkl
  fix_part: lower
  split_index: 12
base:
  enabled: true
  execute: false
  python_executable: /home/xiyv/miniconda3/envs/unitree_rl_mjlab/bin/python
  task_id: Unitree-G1-23Dof-Flat
  num_envs: 128
skill:
  enabled: true
  execute: false
  python_executable: /home/xiyv/miniconda3/envs/unitree-rl/bin/python
  mode: train
  motion_file_mode: from_motion_stage
  motion_asset_id: example_motion_asset
  task_name: g1_skill_motion_tracking
  project_name: MotionTracking
  num_envs: 128
  experiment_name: hybrid_debug
  device: cuda:0
