python_executable: auto
motion:
  enabled: true
  execute: true
  source_file: engines/base_locomotion/src/assets/motions/g1_23dof/jilejingtu.npz
  output_dir: runtime/example_motion
  output_file: runtime/example_motion/example_motion.npz
  fix_part: lower
  split_index: 12
base:
  enabled: true
  execute: false
  python_executable: /home/xiyv/miniconda3/envs/unitree_rl_mjlab/bin/python
  task_id: Unitree-G1-23Dof-Flat
  num_envs: 128
skill:
  enabled: true
  execute: false
  python_executable: /home/xiyv/miniconda3/envs/unitree_rl_mjlab/bin/python
  mode: train
  motion_file_mode: from_motion_stage
  motion_asset_id: example_motion_asset
  task_id: Unitree-G1-23Dof-Tracking
  task_name: Unitree-G1-23Dof-Tracking
  num_envs: 128
  experiment_name: hybrid_debug
